import { StaticImageData } from "next/image";
import img1 from "../../__assets/showcase/image 1.webp";
import img2 from "../../__assets/showcase/image 2.webp";
import img3 from "../../__assets/showcase/image 3.webp";

export const categories = [
    "UGC",
    "Beauty",
    "Fashion",
    "Food",
    "Fitness",
    "Automotive",
];

export type ItemType = { label: string; img: StaticImageData | null };

export const categoryData: Record<string, ItemType[]> = {
    UGC: [
        { label: "UNBOXING", img: img1 },
        { label: "TESTIMONIALS", img: img2 },
        { label: "TRY-ONS", img: img3 },
        { label: "PODCASTS", img: img1 },
        { label: "REVIEWS", img: null },
        { label: "DEMOS", img: null },
        { label: "POV'S", img: null },
        { label: "HOOK + CAPTION STYLE", img: null },
        { label: "I TRIED X FOR 7 DAYS", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
    Beauty: [
        { label: "SKINCARE ROUTINE", img: img2 },
        { label: "MAKEUP TUTORIAL", img: img3 },
        { label: "PRODUCT REVIEW", img: null },
        { label: "BEFORE & AFTER", img: img1 },
        { label: "GET READY WITH ME", img: null },
        { label: "HAUL", img: null },
        { label: "BEAUTY HACKS", img: null },
        { label: "TUTORIAL", img: null },
        { label: "SKINCARE TIPS", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
    Fashion: [
        { label: "OOTD", img: img3 },
        { label: "LOOKBOOK", img: img1 },
        { label: "STYLING TIPS", img: null },
        { label: "FASHION HAUL", img: img2 },
        { label: "THRIFT FLIP", img: null },
        { label: "TREND ALERT", img: null },
        { label: "TRY ON HAUL", img: null },
        { label: "STREET STYLE", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
    Food: [
        { label: "RECIPE TUTORIAL", img: img1 },
        { label: "TASTE TEST", img: img3 },
        { label: "MUKBANG", img: null },
        { label: "COOK WITH ME", img: img2 },
        { label: "GROCERY HAUL", img: null },
        { label: "MEAL PREP", img: null },
        { label: "RESTAURANT REVIEW", img: null },
        { label: "FOOD HACKS", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
    Fitness: [
        { label: "WORKOUT ROUTINE", img: img2 },
        { label: "FORM CHECK", img: img1 },
        { label: "GYM VLOG", img: null },
        { label: "SUPPLEMENT REVIEW", img: img3 },
        { label: "HOME WORKOUT", img: null },
        { label: "MEAL PLAN", img: null },
        { label: "FITNESS JOURNEY", img: null },
        { label: "WARM UP", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
    Automotive: [
        { label: "CAR REVIEW", img: img3 },
        { label: "TEST DRIVE", img: img2 },
        { label: "MODIFICATIONS", img: null },
        { label: "DETAILING", img: img1 },
        { label: "POV DRIVE", img: null },
        { label: "EXHAUST SOUND", img: null },
        { label: "BUILD UPDATE", img: null },
        { label: "CAR MEET", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
        { label: "LOREM IPSUM", img: null },
    ],
};
